title: MNC+Sons Contractors
baseURL: 'https://mnc.netlify.com'
languageCode: en-us
theme: mnc
enableRobotsTXT: true
disableKinds:
  - taxonomy
  - taxonomyTerm
menu:
  main:
    - URL: '#portfolio'
      name: Portfolio
      weight: 1
    - URL: '#about-res'
      name: About us
      weight: 2
    - URL: '#contact'
      name: Contact
      weight: 3
params:
  author: modstud.io
  description: ''
  logo: /assets/images/logo.svg
  no_found_bg: /assets/images/public/commercial.jpg
  no_found_text: Page not found
  robotsTXTtext: |-
    User-agent: *
    Disallow: /
