backend:
  name: git-gateway
  branch: master

local_backend: true

slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

media_folder: "static/assets/images/"
public_folder: "/assets/images/public/"

collections:
  - label: "General"
    name: "general"
    files:
    - label: "General Info"
      name: "general_info"
      file: "config.yml"
      fields:
        - label: "Site Title"
          name: "title"
          widget: "string"
        - label: "Site Domain"
          name: "baseURL"
          widget: "string"
        - label: "Language"
          name: "languageCode"
          widget: "hidden"
        - label: "Theme"
          name: "theme"
          widget: "hidden"
        - label: "Robots"
          name: "enableRobotsTXT"
          widget: "hidden"
        - label: "Disable Kinds"
          name: "disableKinds"
          widget: "hidden"
        - label: "Menu"
          name: "menu"
          widget: "hidden"
          fields:
            - label: "Main Menu"
              name: "main"
              widget: "list"
              fields:
                - {label: "Name", name: "name", widget: "string"}
                - {label: "URL", name: "URL", widget: "string"}
                - {label: "Position", name: "weight", widget: "string"}
        - label: "Parameters"
          name: "params"
          widget: "object"
          fields:
            - name: "logo"
              label: "Logo"
              widget: "image"
            - name: "description"
              label: "Description"
              widget: "text"
              required: false
            - name: "images"
              label: "Meta Image"
              widget: "file"
              required: false
            - name: "author"
              label: "Site Author"
              widget: "string"
              required: false
            - name: "googleAnalitycsID"
              label: "Google Analytics Code"
              widget: "string"
              required: false
            - label: "404 Page Text"
              name: "no_found_text"
              widget: "string"
            - label: "404 Page Background"
              name: "no_found_bg"
              widget: "image"
            - name: "robotsTXTtext"
              label: "Robots.txt"
              widget: text
              required: false
  - label: "Contact"
    name: "contact"
    files:
    - label: "Contact Info"
      name: "contact_info"
      file: "themes/mnc/data/contact.yml"
      fields:
        - label: "Contact Title"
          name: "contact_heading"
          widget: "string"
        - label: "Contact Phone"
          name: "contact_phone"
          widget: "string"
        - label: "Instagram Link"
          name: "instagram"
          widget: "string"
        - label: "New York Address"
          name: "new_york_address"
          widget: "string"
        - label: "New York Link to Google Map"
          name: "new_york_address_link"
          widget: "string"
        - label: "New Jersey Address"
          name: "new_jersey_address"
          widget: "string"
        - label: "New Jersey Link to Google Map"
          name: "new_jersey_address_link"
          widget: "string"
  - label: "Residential"
    name: "residential"
    files:
      - label: "Residential Page Settings"
        name: "residential_settings"
        file: "content/portfolio-residential/_index.md"
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
            required: false
          - label: "Hero Image"
            name: "main_img"
            widget: "image"
          - label: "Section Heading"
            name: "heading"
            widget: "string"
      - label: "About"
        name: "about"
        file: "themes/mnc/data/about_residential.yml"
        fields:
          - label: "Section Heading"
            name: "about_heading"
            widget: "string"
          - label: "Top Section Info"
            name: "top"
            widget: "object"
            fields:
              - label: "Photo"
                name: about_pic
                widget: "image"
              - label: "Heading"
                name: "heading"
                widget: "markdown"
              - label: "Text"
                name: "paragraph"
                widget: "markdown"
              - label: "Years Badge"
                name: "badge"
                widget: "image"
          - label: "Bottom Section Info"
            name: "bottom"
            widget: "object"
            fields:
              - label: "Photo"
                name: "matters_pic"
                widget: "image"
              - label: "Heading"
                name: 'heading'
                widget: "string"
              - label: "Subheading"
                name: "subheading"
                widget: "markdown"
              - label: "Text"
                name: "text"
                widget: "markdown"
              - label: "Additional Info"
                name: giving_back
                widget: "object"
                fields:
                  - label: "Heading"
                    widget: "string"
                    name: "heading"
                  - label: "Text"
                    widget: "markdown"
                    name: "text"
  - label: "Residential Portfolio"
    name: "portfolio-residential"
    folder: "themes/mnc/data/portfolio_residential"
    label_singular: "Residential Item"
    identifier_field: project_name
    create: true
    extension: yml
    sortableFields: ['commit_date', 'favorite', 'project_name']
    view_filters:
      - label: Favorites
        field: favorite
        pattern: ^(?=\d{1}$)1?2?3?4?5?6?$
    fields:
      - label: "Favorite Position"
        name: "favorite"
        widget: "select"
        multiple: false
        required: true
        options:
          - { label: "Not Included", value: '7' }
          - { label: "First", value: '1' }
          - { label: "Second", value: '2' }
          - { label: "Third", value: '3' }
          - { label: "Fourth", value: '4' }
          - { label: "Fifth", value: '5' }
          - { label: "Sixth", value: '6' }
        default: '7'
      - label: "Project Name"
        name: "project_name"
        widget: "string"
        hint: "Not shown on the site. Added to simplify project administration"
      - label: "Main Image"
        name: "picture"
        widget: "image"
      - label: "Address"
        name: "address"
        widget: "string"
        required: false
      - label: "Job Description"
        name: "type"
        widget: "string"
        required: false
      - label: "Square Feet"
        name: "area"
        widget: "string"
        required: false
      - label: "Architect"
        name: "architect"
        widget: "string"
        required: false
      - label: "Designer"
        name: "design"
        widget: "string"
        required: false
      - label: "Exterior Images"
        name: exterior_pictures
        widget: "list"
        label_singular: "Image"
        fields:
          - label: "Exterior Image"
            name: "gallery_img"
            widget: "image"
      - label: "Interior Images"
        name: interior_pictures
        widget: "list"
        label_singular: "Image"
        fields:
          - label: "Interior Image"
            name: "gallery_img"
            widget: "image"
  - label: "Commercial"
    name: "commercial"
    files:
      - label: "Commercial Page Settings"
        name: "commercial_settings"
        file: "content/portfolio-commercial/_index.md"
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
            required: false
          - label: "Hero Image"
            name: "main_img"
            widget: "image"
          - label: "Section Heading"
            name: "heading"
            widget: "string"
      - label: "About"
        name: "about"
        file: "themes/mnc/data/about_commercial.yml"
        fields:
          - label: "Section Heading"
            name: "about_heading"
            widget: "string"
          - label: "Top Section Info"
            name: "top"
            widget: "object"
            fields:
              - label: "Photo"
                name: "about_pic"
                widget: "image"
              - label: "Heading"
                name: "heading"
                widget: "markdown"
              - label: "Text"
                name: "paragraph"
                widget: "markdown"
              - label: "Years Badge"
                name: "badge"
                widget: "image"
          - label: "Bottom Section Info"
            name: "bottom"
            widget: "object"
            fields:
              - label: "Heading"
                name: "heading"
                widget: "string"
              - label: "Subheading"
                name: "subheading"
                widget: "markdown"
              - label: "Second Heading"
                name: "heading_bottom"
                widget: "string"
              - label: "Second Subheading"
                name: "subheading_bottom"
                widget: "markdown"
              - label: "Info Block"
                name: "block"
                widget: "object"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Text Block"
                    name: "textblock"
                    widget: "object"
                    fields:
                      - label: "Heading"
                        name: "heading"
                        widget: "string"
                      - label: "Text"
                        name: "text"
                        widget: "markdown"
  - label: "Commercial Portfolio"
    name: "portfolio-commercial"
    folder: "themes/mnc/data/portfolio_commercial"
    label_singular: "Commercial Item"
    identifier_field: name
    create: true
    extension: yml
    sortableFields: ['commit_date', 'favorite', 'name']
    view_filters:
      - label: Favorites
        field: favorite
        pattern: ^(?=\d{1}$)1?2?3?4?5?6?$
    fields:
      - label: "Favorite Position"
        name: "favorite"
        widget: "select"
        multiple: false
        required: true
        options:
          - { label: "Not Included", value: '7' }
          - { label: "First", value: '1' }
          - { label: "Second", value: '2' }
          - { label: "Third", value: '3' }
          - { label: "Fourth", value: '4' }
          - { label: "Fifth", value: '5' }
          - { label: "Sixth", value: '6' }
        default: '7'
      - label: "Project Name"
        name: "name"
        widget: "string"
      - label: "Main Image"
        name: "picture"
        widget: "image"
      - label: "Address"
        name: "address"
        widget: "string"
        required: false
      - label: "Job Description"
        name: "type"
        widget: "string"
        required: false
        hint: "Ignored if project contains sub projects"
      - label: "Square Feet"
        name: "area"
        widget: "string"
        required: false
        hint: "Ignored if project contains sub projects"
      - label: "Approx. Cost"
        name: "price"
        widget: "string"
        required: false
        hint: "Ignored if project contains sub projects"
      - label: "Architect"
        name: "architect"
        widget: "string"
        required: false
        hint: "Ignored if project contains sub projects"
      - label: "Designer"
        name: "design"
        widget: "string"
        required: false
        hint: "Ignored if project contains sub projects"
      - label: "Exterior Images"
        name: exterior_pictures
        hint: "Ignored if project contains sub projects"
        widget: "list"
        label_singular: "Image"
        fields:
          - label: "Exterior Image"
            name: "gallery_img"
            widget: "image"
      - label: "Interior Images"
        name: interior_pictures
        hint: "Ignored if project contains sub projects"
        widget: "list"
        label_singular: "Image"
        fields:
          - label: "Interior Image"
            name: "gallery_img"
            widget: "image"
      - label: "Portfolio Sub Items"
        name: "sub_item"
        widget: "list"
        label_singular: "Portfolio Sub Item"
        fields:
          - label: "Sub Project Name"
            name: "name"
            widget: "string"
            required: false
          - label: "Main Image"
            name: "picture"
            widget: "image"
            required: false
          - label: "Type"
            name: "type"
            widget: "string"
            required: false
          - label: "Area"
            name: "area"
            widget: "string"
            required: false
          - label: "Price"
            name: "price"
            widget: "string"
            required: false
          - label: "Architect"
            name: "architect"
            widget: "string"
            required: false
          - label: "Design"
            name: "design"
            widget: "string"
            required: false
          - label: "Exterior Images"
            name: exterior_pictures
            widget: "list"
            label_singular: "Image"
            fields:
              - label: "Exterior Image"
                name: "gallery_img"
                widget: "image"
          - label: "Interior Images"
            name: interior_pictures
            widget: "list"
            label_singular: "Image"
            fields:
              - label: "Interior Image"
                name: "gallery_img"
                widget: "image"
