backend:
  name: git-gateway
  branch: master

local_backend: true

slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"

media_folder: "static/assets/images/"
public_folder: "/assets/images/public/"

collections:
  - label: "General"
    name: "general"
    files:
    - label: "General Info"
      name: "general_info"
      file: "config.yml"
      fields:
        - label: "Site Title"
          name: "title"
          widget: "string"
        - label: "Site Domain"
          name: "baseURL"
          widget: "string"
        - label: "Language"
          name: "languageCode"
          widget: "hidden"
        - label: "Theme"
          name: "theme"
          widget: "hidden"
        - label: "Robots"
          name: "enableRobotsTXT"
          widget: "hidden"
        - label: "Disable Kinds"
          name: "disableKinds"
          widget: "hidden"
        - label: "Menu"
          name: "menu"
          widget: "hidden"
          fields:
            - label: "Main Menu"
              name: "main"
              widget: "list"
              fields:
                - {label: "Name", name: "name", widget: "string"}
                - {label: "URL", name: "URL", widget: "string"}
                - {label: "Position", name: "weight", widget: "string"}
        - label: "Parameters"
          name: "params"
          widget: "object"
          fields:
            - name: "logo"
              label: "Logo"
              widget: "image"
            - name: "description"
              label: "Description"
              widget: "text"
              required: false
            - name: "images"
              label: "Meta Image"
              widget: "file"
              required: false
            - name: "author"
              label: "Site Author"
              widget: "string"
              required: false
            - name: "googleAnalitycsID"
              label: "Google Analytics Code"
              widget: "string"
              required: false
            - label: "404 Page Text"
              name: "no_found_text"
              widget: "string"
            - label: "404 Page Background"
              name: "no_found_bg"
              widget: "image"
            - name: "robotsTXTtext"
              label: "Robots.txt"
              widget: text
              required: false
  - label: "Contact"
    name: "contact"
    files:
    - label: "Contact Info"
      name: "contact_info"
      file: "themes/mnc/data/contact.yml"
      fields:
        - label: "Contact Title"
          name: "contact_heading"
          widget: "string"
        - label: "Contact Phone"
          name: "contact_phone"
          widget: "string"
        - label: "Instagram Link"
          name: "instagram"
          widget: "string"
        - label: "New York Address"
          name: "new_york_address"
          widget: "string"
        - label: "New York Link to Google Map"
          name: "new_york_address_link"
          widget: "string"
        - label: "New Jersey Address"
          name: "new_jersey_address"
          widget: "string"
        - label: "New Jersey Link to Google Map"
          name: "new_jersey_address_link"
          widget: "string"
  - label: "Residential"
    name: "residential"
    files:
      - label: "Residential Page Settings"
        name: "residential_settings"
        file: "content/portfolio-residential/_index.md"
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
            required: false
          - label: "Hero Image"
            name: "main_img"
            widget: "image"
          - label: "Section Heading"
            name: "heading"
            widget: "string"
      - label: "About"
        name: "about"
        file: "themes/mnc/data/about_residential.yml"
        fields:
          - label: "Section Heading"
            name: "about_heading"
            widget: "string"
          - label: "Top Section Info"
            name: "top"
            widget: "object"
            fields:
              - label: "Photo"
                name: about_pic
                widget: "image"
              - label: "Start Date"
                name: "year"
                widget: "datetime"
                dateFormat: "YYYY/MM/DD"
                hint: "The amount of years in business displayed on this page will count from this date."
              - label: "Heading"
                name: "heading"
                widget: "markdown"
              - label: "Left column Paragraph"
                name: "paragraph_1"
                widget: "markdown"
              - label: "Right column Paragraph"
                name: "paragraph_2"
                widget: "markdown"
          - label: "Bottom Section Info"
            name: "bottom"
            widget: "object"
            fields:
              - label: "Photo"
                name: "family_pic"
                widget: "image"
                required: false
              - label: "Left column Blocks"
                name: "left_column"
                widget: "list"
                label_singular: "Left column Block"
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: "markdown"
                  - label: "Text"
                    name: "text"
                    widget: "markdown"
              - label: "Right column Block"
                name: "right_column"
                widget: "object"
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: "string"
                  - label: "Subheading"
                    name: "subheading"
                    widget: "markdown"
                  - label: "Text"
                    name: "text"
                    widget: "markdown"
                  - label: "Text Blocks"
                    name: "block"
                    widget: "list"
                    label_singular: "Text Block"
                    fields:
                      - label: "Heading"
                        name: "heading"
                        widget: "markdown"
                      - label: "Text"
                        name: "text"
                        widget: "markdown"
  - label: "Residential Portfolio"
    name: "portfolio-residential"
    folder: "themes/mnc/data/portfolio_residential"
    label_singular: "Residential Item"
    identifier_field: project_name
    create: true
    extension: yml
    view_filters:
      - label: Favorites
        field: favorite
        pattern: '[^(?=\d{5}$)1?2?3?4?5?6?7?8?9?0?$]'
    fields:
      - label: "Favorite Position"
        name: "favorite"
        widget: "number"
        min: 0
        max: 6
        hint: "Please, select the position in Favorites. From '1' to '6'. '0' excludes item from Favorites"
        required: false
      - label: "Project Name"
        name: "project_name"
        widget: "string"
        hint: "Not shown on the site. Added to simplify project administration"
      - label: "Main Image"
        name: "picture"
        widget: "image"
      - label: "Address"
        name: "address"
        widget: "string"
        required: false
      - label: "Job Description"
        name: "type"
        widget: "string"
        required: false
      - label: "Square Feet"
        name: "area"
        widget: "string"
        required: false
      - label: "Architect"
        name: "architect"
        widget: "string"
        required: false
      - label: "Designer"
        name: "design"
        widget: "string"
        required: false
      - label: "Images"
        name: gallery_pictures
        widget: "list"
        label_singular: "Image"
        fields:
          - label: "Gallery Image"
            name: "gallery_img"
            widget: "image"
  - label: "Commercial"
    name: "commercial"
    files:
      - label: "Commercial Page Settings"
        name: "commercial_settings"
        file: "content/portfolio-commercial/_index.md"
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
            required: false
          - label: "Hero Image"
            name: "main_img"
            widget: "image"
          - label: "Section Heading"
            name: "heading"
            widget: "string"
      - label: "Portfolio"
        name: "portfolio"
        file: "themes/mnc/data/portfolio_commercial.yml"
        fields:
          - label: "Portfolio Items"
            name: "portfolio_item"
            widget: "list"
            label_singular: "Portfolio Item"
            fields:
              - label: "Project Name"
                name: "name"
                widget: "string"
              - label: "Main Image"
                name: "picture"
                widget: "image"
              - label: "Address"
                name: "address"
                widget: "string"
                required: false
              - label: "Job Description"
                name: "type"
                widget: "string"
                required: false
                hint: "Ignored if project contains sub projects"
              - label: "Square Feet"
                name: "area"
                widget: "string"
                required: false
                hint: "Ignored if project contains sub projects"
              - label: "Approx. Cost"
                name: "price"
                widget: "string"
                required: false
                hint: "Ignored if project contains sub projects"
              - label: "Architect"
                name: "architect"
                widget: "string"
                required: false
                hint: "Ignored if project contains sub projects"
              - label: "Designer"
                name: "design"
                widget: "string"
                required: false
                hint: "Ignored if project contains sub projects"
              - label: "Images"
                name: gallery_pictures
                widget: "list"
                required: false
                hint: "Ignored if project contains sub projects"
                label_singular: "Image"
                fields:
                  - label: "Gallery Image"
                    name: "gallery_img"
                    widget: "image"
              - label: "Portfolio Sub Items"
                name: "sub_item"
                widget: "list"
                label_singular: "Portfolio Sub Item"
                fields:
                  - label: "Sub Project Name"
                    name: "name"
                    widget: "string"
                    required: false
                  - label: "Main Image"
                    name: "picture"
                    widget: "image"
                    required: false
                  - label: "Type"
                    name: "type"
                    widget: "string"
                    required: false
                  - label: "Area"
                    name: "area"
                    widget: "string"
                    required: false
                  - label: "Price"
                    name: "price"
                    widget: "string"
                    required: false
                  - label: "Architect"
                    name: "architect"
                    widget: "string"
                    required: false
                  - label: "Design"
                    name: "design"
                    widget: "string"
                    required: false
                  - label: "Images"
                    name: gallery_pictures
                    widget: "list"
                    label_singular: "Image"
                    fields:
                      - label: "Gallery Image"
                        name: "gallery_img"
                        widget: "image"
      - label: "About"
        name: "about"
        file: "themes/mnc/data/about_commercial.yml"
        fields:
          - label: "Section Heading"
            name: "about_heading"
            widget: "string"
          - label: "Top Section Info"
            name: "top"
            widget: "object"
            fields:
              - label: "Photo"
                name: about_pic
                widget: "image"
              - label: "Start Date"
                name: "year"
                widget: "datetime"
                hint: "The amount of years in business displayed on this page will count from this date."
                dateFormat: "YYYY/MM/DD"
              - label: "Heading"
                name: "heading"
                widget: "markdown"
              - label: "Left column Paragraph"
                name: "paragraph_1"
                widget: "markdown"
              - label: "Right column Paragraph"
                name: "paragraph_2"
                widget: "markdown"
          - label: "Bottom Section Info"
            name: "bottom"
            widget: "object"
            fields:
              - label: "Photo"
                name: "family_pic"
                widget: "image"
                required: false
              - label: "Left column Blocks"
                name: "left_column"
                widget: "list"
                label_singular: "Left column Block"
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: "markdown"
                  - label: "Text"
                    name: "text"
                    widget: "markdown"
              - label: "Right column Block"
                name: "right_column"
                widget: "object"
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: "string"
                  - label: "Subheading"
                    name: "subheading"
                    widget: "markdown"
                  - label: "Text"
                    name: "text"
                    widget: "markdown"
                  - label: "Two column Blocks"
                    name: "two_column_block"
                    widget: "list"
                    label_singular: "Two column Block"
                    fields:
                      - label: "Heading"
                        name: "heading"
                        widget: "markdown"
                      - label: "Text"
                        name: "text"
                        widget: "markdown"
                  - label: "Text Blocks"
                    name: "block"
                    widget: "list"
                    label_singular: "Text Block"
                    fields:
                      - label: "Heading"
                        name: "heading"
                        widget: "markdown"
                      - label: "Text"
                        name: "text"
                        widget: "markdown"
